version: '3.8'
services:
  backend:
    image: python:3.11
    container_name: ai-analytic-backend
    working_dir: /app
    ports:
      - "0.0.0.0:${BACKEND_PORT:-8002}:8002"
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SERVER_HOST=0.0.0.0
      - BACKEND_PORT=${BACKEND_PORT:-8002}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    command: >
      bash -c "echo 'DATABASE_URL:' $DATABASE_URL &&
               pip install --no-cache-dir -r requirements.txt &&
               pip install pdfplumber &&
               uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Сервіс фронтенду на React
#   frontend:
#     image: node:20
#     container_name: ai-analytic-frontend
#     working_dir: /app
#     ports:
#       - "0.0.0.0:${FRONTEND_PORT:-3000}:3000"
#     volumes:
#       - ./frontend:/app
#       - node_modules:/app/node_modules
#     env_file: 
#       - ./.env
#     environment:
#       - REACT_APP_API_URL=${REACT_APP_API_URL:-http://${SERVER_HOST:-localhost}:${BACKEND_PORT:-8002}}
#       - NODE_ENV=development
#       - WDS_SOCKET_HOST=0.0.0.0
#       - FRONTEND_PORT=${FRONTEND_PORT:-3000}
#       - CHOKIDAR_USEPOLLING=true
#     command: >
#       bash -c "npm ci --force &&
#                npm start"
#     networks:
#       - app-network
#     restart: unless-stopped
#     depends_on:
#       - backend

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   node_modules: