"""add price per_w to solar_panel

Revision ID: 3759f977bbad
Revises: f3bde208313a
Create Date: 2025-06-06 15:49:56.038091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3759f977bbad'
down_revision: Union[str, None] = 'f3bde208313a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_panels_prices', sa.Column('price_per_w', sa.Float(), nullable=False))
    op.add_column('solar_panels_prices_current', sa.Column('price_per_w', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solar_panels_prices_current', 'price_per_w')
    op.drop_column('solar_panels_prices', 'price_per_w')
    # ### end Alembic commands ###
