"""upd inverters firmware

Revision ID: a61282724dc4
Revises: e349342bbb02
Create Date: 2025-06-02 11:11:48.497316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61282724dc4'
down_revision: Union[str, None] = 'e349342bbb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inverters', 'firmware',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inverters', 'firmware',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
