"""upd tables

Revision ID: e8966ebe1d24
Revises: a2897c539275
Create Date: 2025-05-30 14:46:32.409316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8966ebe1d24'
down_revision: Union[str, None] = 'a2897c539275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_status_id'), 'supplier_status', ['id'], unique=False)
    op.add_column('batteries_suppliers', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batteries_suppliers', 'supplier_status', ['status_id'], ['id'])
    op.add_column('inverters_suppliers', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inverters_suppliers', 'supplier_status', ['status_id'], ['id'])
    op.add_column('solar_panels_suppliers', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solar_panels_suppliers', 'supplier_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solar_panels_suppliers', type_='foreignkey')
    op.drop_column('solar_panels_suppliers', 'status_id')
    op.drop_constraint(None, 'inverters_suppliers', type_='foreignkey')
    op.drop_column('inverters_suppliers', 'status_id')
    op.drop_constraint(None, 'batteries_suppliers', type_='foreignkey')
    op.drop_column('batteries_suppliers', 'status_id')
    op.drop_index(op.f('ix_supplier_status_id'), table_name='supplier_status')
    op.drop_table('supplier_status')
    # ### end Alembic commands ###
