"""add panel color

Revision ID: f0d0a843ca65
Revises: 724c80650701
Create Date: 2025-06-06 11:41:01.330248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d0a843ca65'
down_revision: Union[str, None] = '724c80650701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_panels', sa.Column('panel_color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solar_panels', 'panel_color')
    # ### end Alembic commands ###
